analogdevicesinc/adi-kuiper-gen

export-image/prerun.sh
This partion will be used to store the preloader for Intel/Altera FPGAs.
=> export-image: Create a third partion for Intel FPGAs

stage2/EXPORT_IMAGE, stage2/EXPORT_NOOBS, stage3/00-install-packages/00-packages, stage4/EXPORT_IMAGE, stage4/EXPORT_NOOBS, stage5/EXPORT_IMAGE, stage5/EXPORT_NOOBS, stage6/01-install-packages/00-packages, stage6/04-gnuradio-m2k/00-run.sh, stage6/06-cosmetic/00-run.sh
The PR contains a set of fixes targeted to fbturbo issue on 32 bit systems aside RPI (ex. Altera, Xilinx) and a fix for the qwt and qwt polar packages used for Scopy.
=> Fixes qwt fbturbo

stage6/04-gnuradio-m2k/00-run.sh
This patch add Scopy to ADI Kuiper Image.
=> stage6: 04-gnuradio-m2k: Add scopy build

export-image/prerun.sh, stage8/02-extra-boot/00-run.sh
This patch will write a default preloader for Altera devices.
=> extra-boot: Write preloader for Altera platforms

stage6/01-install-packages/00-packages, stage6/07-aditof-sdk/00-run.sh
The sdk will be cloned in /home/analog/workspace/github/aditof_sdk
A shortcut to use the demo will be placed on the desktop
Signed-off-by: DanielGuramulta <Daniel.Guramulta@analog.com>
=> stage6: add aditof_sdk to the build process

stage6/01-install-packages/00-packages
=> stage6: Add vim package

stage8/EXPORT_NOOBS
This reverts commit 0070062228496c2c18b1657a7a3d7212ac740305.
=> Revert "stage8: Only generate full image"

stage4/01-console-autologin/00-run.sh, stage6/01-install-packages/00-packages, stage6/04-gnuradio-m2k/00-run.sh
Cherry pick commits from 2019_R2 that are not in master branch.
=> Bring changes from 2019 r2

stage4/01-console-autologin/00-run.sh
Add ttyS0 to securetty.
Signed-off-by: Sergiu Cuciurean <sergiu.cuciurean@analog.com>
=> stage4: 01-console-autologin: Autologin on S0

stage5/00-install-extras/00-packages
=> stage5: 00-install-extras: remove nodered package

.dockerignore, .gitignore, config
Remove config from default .gitignore file because config is mandatory at build.
=> gitignore: delete config

stages/04.configure-desktop-env/03.cosmetic/run.sh
Create "Analog Devices tools" menu category.
=> stages/04.configure-desktop-env/03.cosmetic: create menu category

README.md, azure-pipelines.yml, ci/modify_config.sh, kuiper-stages.sh, stages/01.bootstrap/run.sh
Add yaml file in order to build Kuiper2.0 images on Azure Devops platform.
=> Staging/ci kuiper2.0

README.md
Update libm2k and grm2k branches to main.
Add information about the RPI package repository.
Fix typos.
=> README.md: update and fix typos

stages/03.system-users-and-autologin/01.create-system-users/run.sh
Change hostname from 'kuiper' to 'analog'.
=> stages/03.system-users-and-autologin/01.create-system-users: Change hostname to 'analog'.

stages/02.set-locale-and-timezone/03.mandatory-packages/00.install-packages/packages
'usbutils' provides useful commands like 'lsusb', 'usb-devices', etc.
=> Install usbutils

stages/05.adi-tools/13.install-linux_image_ADI-scripts/run.sh
Install scripts from 'linux_image_ADI-scripts' repo.
=> stages/05.adi-tools: install linux_image_ADI-scripts

stages/02.set-locale-and-timezone/03.mandatory-packages/00.install-packages/packages
'device-tree-compiler' package provides commands like fdtput and fdtget (used by scripts in 'linux_image_ADI-scripts')
=> Install device-tree-compiler package

.github/workflows/kuiper2_0-build.yml
Change runner of 32 full configuration to a self hosted one
=> Change runner for the 32 full configuration build

stages/02.set-locale-and-timezone/03.mandatory-packages/run.sh
xserver-xorg is needed to open GUI applications via ssh without a desktop environment.
=> Install xserver-xorg by default

.github/workflows/docker-image-build.yml
In order to upload the packages on github permissions needs to be set.
=> Add permission for docker package upload

stages/02.set-locale-and-timezone/03.mandatory-packages/00.install-packages/packages
Install bash-completion package to enhance the command-line interface by providing autocompletion.
=> Install bash-completion package

stage6/04-gnuradio-m2k/00-run.sh
Remove Volk build
Remove ppa repository for GNU Radio
Rename install function for GNU Radio
=> Update gnuradio version

stage6/04-gnuradio-m2k/00-run.sh
Remove Volk build
Remove ppa repository for GNU Radio
Rename install function for GNU Radio
=> Update GNU Radio installation

stage6/03-pyadi/00-run.sh, stage6/04-gnuradio-m2k/00-run.sh, stage8/00-license-generation/00-run.sh
Bring the latest updates from 2023_R2 to main
=> Update to latest

stages/03.system-tweaks/05.automount/run.sh
Modify the kernel logging levels to reduce noise in the console while keeping critical messages.
=> Suppress log printing

Dockerfile
Replace deprecated syntax in Dockerfile
=> Dockerfile: fix deprecated ENV format

stages/07.extra-tweaks/02.install-rpi-packages/run.sh
Change deprecated package `python3-rpi.gpio` to `python3-rpi-lgpio`
=> 07.extra-tweaks/02.install-rpi-packages: Update RPI GPIO package

stage2/01-sys-tweaks/00-packages, stage4/00-install-packages/00-packages
Change deprecated package python3-rpi.gpio to python3-rpi-lgpio 
Remove package installation from stage4 (duplicate)
=> stage2: Update RPI GPIO package

stage1/00-boot-files/files/config.txt
Enable DWC2 host mode support for CM5 by default
=> stage1/00-boot-files/config: Add support for CM5

stages/08.export-stage/03.generate-license/run-chroot.sh
Check if linux_image_ADI-scripts is installed before converting license to HTML.
=> 08.export-stage/03.generate-license: Update LICENSE file

LICENSE, NOTICE, stages/08.export-stage/03.generate-license/run-chroot.sh
Update LICENSE for 2025
Add NOTICE with links to contents
Update ADI address in LICENSE.html
=> LICENSE and NOTICE: update info 

azure-pipelines.yml
Since staging/kuiper2.0 branch became main, the branch that is build by GitHub Actions needs to be main as well.
=> azure-pipelines.yml: Update build branch

README.md
Since branch staging/kuiper2.0 became main, the clone command should also change to main.
=> README.md: Update clone branch

.github/workflows/docker-image-build.yml, .github/workflows/kuiper2_0-build.yml, README.md
Update triggers from workflows to main branch.
Modify the status badge to point to main branch builds.
=> Update trigger to main branch

README.md
=> README.md: Refactor documentation

build-docker.sh, stages/05.adi-tools/14.write-git-logs/run.sh
Update git log script to include tags as an alternative to branches.
Save current adi-kuiper-gen repository details to git log file.
=> Fix repos script

.github/CODEOWNERS
=> .github/CODEOWNERS: add codeowners
