- Dockerfile
- depends
- stage7/00-console-autologin/00-run.sh
- stage7/01-adi-kernel-dts/00-run.sh
- stage7/EXPORT_IMAGE
- stage7/EXPORT_NOOBS
- stage7/prerun.sh
This patch adds a separate stage for kernel build. This will clone the
linux-adi repository and build the kernel, dts and modules for raspberry
pi.
> stage7: Add kernel build stage

- stage3/00-install-packages/00-packages
This packages is required by the jesd_status/eyescan application.
> stage3: install-packages: Install GTK3 package

- stage6/03-gr-iio/00-run.sh
This patch will set the install prefix for cmake configuration to /usr.
Fixes: 879b8c03e386 ("stage6: Add gr-iio to the build")
> stage6: gr-iio: Fix install prefix for gr-iio

- stage2/01-sys-tweaks/01-run.sh
Will investigate more when USBD will be added with a watcher for changes to the usb_gadget folder. It seems that iiod service is installed but not enabled so this is required for iiod to be running at startup.
> Revert "stage2: sys-tweaks: Remove iiod service file"

- stage6/02-adi-update-tools/00-run.sh
To have a stable set of applications this build has been shifted to the
release branch 2019_R2. Also the linux_image_ADI_scripts will not be
removed to have them available for future use.
> stage6: Add 2019_R2 option to adi_update_tools

- stage6/01-install-packages/00-packages
This packages is used to enable libiio usb banckend.
> stage6: packages: Add libusb-1.0

- build.sh
- stage8/02-extra-boot/00-run.sh
Extend folder level to l3 to be able to wget all the necessary files.
> stage8: extra-boot: Extend folder level

- stage6/04-gnuradio-m2k/00-run.sh
Before this patch udev rules where not installed for libm2k this was
causing m2k board to not be visible inside scopy. This removes the cmake
option to not install udev rules.
> stage6: libm2k: Add udev rules to cmake

- stage6/01-install-packages/00-packages
Thsi is used to get correct time and date from an external server.
> stage6: hptdate: Add htpdate package

- stage6/01-install-packages/00-packages
- stage6/07-aditof-sdk/00-run.sh
This pull request adds aditof_sdk to the kuiper images:
The sdk will be cloned in /home/analog/workspace/github/aditof_sdk
A shortcut to use the demo will be placed on the desktop
Signed-off-by: DanielGuramulta <Daniel.Guramulta@analog.com>
> stage6: add aditof_sdk to the build process

- stage4/01-console-autologin/00-run.sh
For ZynqMP platforms the ttyPS0 interface is used for serial communication.
In order for automatic root login on ttyPS0 to work it must be include in
/etc/securetty.
> stage4: Add ttyPS0 to securetty

- stage7/01-adi-kernel-dts/00-run.sh
This patch moves all rpi build to kernel 5.4.
> stage7: Shift to kernel 5.4 for RPI

- stage6/08-eepromutil/00-run.sh
These utilities are used to create, flash and dump HAT EEPROM images.
> stage6: Add eepromutils

- stage8/EXPORT_NOOBS
This reverts commit dbd9497f7ed907452f7caa63d9249e7bfc3c127a.
> Revert "stage8: Only generate full image"

- stage8/00-license-generation/00-run.sh
- stage8/00-license-generation/LICENSE.md
This patch renames the License.md file to match the one requested in the
script - LICENSE.md. Also the "Written Offer" section was added.
> stage8: Fix license generation

- stage6/07-aditof-sdk/00-run.sh
ADITOF-SDK was using one core of the controller at 100% all the time. This
patch changes the tag used for building the software for ADI Kuiper to use
the fixed version.
> stage6: aditof-sdk: Fix process using 100% of cpu core

- export-image/01-set-sources/01-run.sh
Comment 'apt-get update' and 'apt-get dist-upgrade' in export_image since the same commands are also run in first stages.
> export_image: comment 'update' and 'dist-upgrade' commands and print extra logs

- stage6/06-cosmetic/00-run.sh
Commit 3cd5e83 introduced a bug regarding deletion of a file.
Replace file exists condition with just 'rm -f <file name>'.
Using '-f' option will suppress output if the file does not exists.
> stage6:06-cosmetic:00-run.sh: fix file deletion

- stage8/02-extra-boot/00-run.sh
This change prevents the build from failing if EXTRA_BOOT is
missing.
Signed-off-by: Sergiu Cuciurean <sergiu.cuciurean@analog.com>
> stage8: extra_boot: Fix envvar

- stage6/01-install-packages/00-packages
Add dummy xorg package for boards without any video ports.
Signed-off-by: Sergiu Cuciurean <sergiu.cuciurean@analog.com>
> stage6: Add dummy xorg package

- stage6/04-gnuradio-m2k/00-run.sh
Scopy is installed through flatpak and this will create also a shortcut
in Kuiper menu. The shortcut works fine, but its icon is broken.
This commit fix the menu icon of flatpak created shortcut and removes
the extra shortcut (/usr/share/applications/Scopy.desktop).
> stage6:04-gnuradio-m2k: Remove one Scopy shortcut

- stage6/04-gnuradio-m2k/00-run.sh
Remove libsigrokdecode build since it is used by clients very rarely.
> stage6:04-gnuradio-m2k: remove libsigrokdecode

- stage6/03-pyadi/00-run.sh
- stage6/04-gnuradio-m2k/00-run.sh
Update gnuradio-grc.desktop to open Gnu Radio from menu with parameter
"PYTHONPATH=usr/local/lib/python3/dist-packages:/lib/python3.9/site-packages"
This will load correct iio, gr-iio instead of ADI libiio.
Fix also a typo in PYTHONPATH variable from bashrc.
> stage6:04-gnuradio-m2k: fix iio import in gnuradio

- stage2/01-sys-tweaks/00-packages
- stage2/01-sys-tweaks/01-run.sh
'rpi-update' package is installed by default on pi-gen and can be used to
upgrade bootfiles and firmware. This is the old method that, from some reasons,
was kept on pi-gen. New method uses packages 'raspberrypi-bootloader' and
'raspberrypi-kernel' with their dependencies to do the same things. They are
upgradable by "apt-get update/upgrade" command.
RPI4 don't use /boot/bootcode.bin but uses eeprom instead. File on eeprom can be
updated using 'rpi-eeprom' package. By default rpi-eeprom-update service runs at
startup and prompts for applying new updates if there are.
https://raspberrypi.stackexchange.com/questions/4355/do-i-still-need-rpi-update-if-i-am-using-the-latest-version-of-raspbian
https://forums.raspberrypi.com/viewtopic.php?t=281519#p1705079 …
> stage2/01-sys-tweaks: disable RPI bootfiles update

- stage6/03-pyadi/00-run.sh
Do not set PYTHONPATH on /home/analog/.bashrc since this will broke 
loading libiio properly. In this way, python will look for libs only in default paths. 
On gnuradio side, gr-iio are loader properly when gnuradio is open from
Kuiper Menu (fixed with commit 1b52286).
> stage6/03: remove PYTHONPATH from .bashrc

- stage4/00-install-packages/00-packages
GnuRadio Companion fails to open due to missing libcblas.so3 library.
I seems that this was added by libcblas-dev package which got changed
to libatlas-base-dev.
> 00-packages: add libatlas-base-dev package

- stage7/01-adi-kernel-dts/00-run.sh
Commit 335280fb ("stage7/01-adi-kernel: remove building RPI kernels") changed the script to download already built files (kernels, devicetrees, overlays and modules) instead of building them, decreasing in this way total build time of Kuiper. 
At that time, we decided to delete all default files (kernels, dts etc) but since we are not building everything, some RPI versions (like RPI Zero W , RPI Zero 2W) will not boot anymore since they don't have all necessary boot files.
Let all default boot files and only overwrite the ones built by ADI.
> stage7:adi-kernel-dts: let default kernels and DTS

- stage6/04-gnuradio-m2k/00-run.sh
Change gr-m2k branch to be built from 'master' to 'maint-3.8', since this branch is still using GnuRadio 3.8. Master branch got updated to 3.10 GnuRadio version.
> stage6: 04-gnuradio-m2k: switch gr-m2k to 'maint-3.8'

- stage5/01-ldconfig/00-run.sh
- stage8/00-license-generation/00-run.sh
Add 'ldconfig' command after installing all packages from stage5 otherwise stage6/01-install-packages step will fail on build
because it wont find /lib/ld-linux-armhf.so.3 library.
Update "Written Offer" surface-mail address to point to the OSPO and fix typos.
Add ADI components in /home/analog/LICENCE.html file.
> Update license master

- stage7/01-adi-kernel-dts/00-run.sh
Delete all default files because now we have RPI Zero W , RPI Zero 2W on SWDownloads
Signed-off-by: Raluca Groza <raluca.groza@analog.com>
> Delete all default files - 2021_R2

- stage7/01-adi-kernel-dts/00-run.sh
Delete all default files because now we have RPI Zero W , RPI Zero 2W on SWDownloads.
Signed-off-by: Raluca Groza <raluca.groza@analog.com>
> Delete all default files

- stage6/01-install-packages/00-packages
These packages are required for a full installation of Jupyter Notebook.
Signed-off-by: Raluca Groza <raluca.groza@analog.com>
> Install jupyter and python3-matplotlib

- stage6/01-install-packages/00-packages
These packages are required for a full installation of Jupyter Notebook.
Signed-off-by: Raluca Groza <raluca.groza@analog.com>
> 2021_R2 - Install jupyter and python3-matplotlib

- stage7/01-adi-kernel-dts/00-run.sh
With this change only the .dtbo files will be removed so README file will stay available for overlays.
Signed-off-by: Raluca Chis <raluca.chis@analog.com>
> Delete only .dtbo files - 2021_R2

- stage7/01-adi-kernel-dts/00-run.sh
With this change only the .dtbo files will be removed so README file will stay available for overlays.
Signed-off-by: Raluca Chis <raluca.chis@analog.com>
> Delete only .dtbo files

- stage5/00-install-extras/00-packages
- stage6/01-install-packages/00-packages
- stage6/09-sense-emu/00-run.sh
- stage6/09-sense-emu/files/sense_emu_gui.svg
Since apt does not update sense-emu to the latest release (with fix on numpy issue), we will install using pip.
Desktop icon is also manually added
> install sense-emu using pip

- stage6/01-install-packages/00-packages
Install libopenblas-dev since it adds necessary dependencies for numpy. 
In previous versions of numpy, all dependencies were included, so OpenBLAS was not necessary.
Latest numpy switched back, and uses files added by libopenblas-dev package.
> stage6: add libopenblas-dev package required by RPi Sense Emulator GUI

- stage6/01-install-packages/00-packages
- stage6/02-adi-update-tools/00-run.sh
There is package "libopenblas-dev" added  to fix GnuRadio and RPI Sense Emulator.
And switching the default branch of linux_image_ADI-scripts repos, so adi_update_tools.sh. 
In this repo, we'll still need to keep also 'master' in parallel with main, since old versions of the script (updates from older Kuiper images) will look for it.
> Bring changes from 2022_R2 branch back to main

- stage6/02-adi-update-tools/00-run.sh
Remove gtkdatabox-1.0.0.tar.gz after is unpacked and installed because every time there is ran adi_update_tools.sh a new copy will be downloaded with a number appended at the end (ex. gtkdatabox-1.0.0.tar.gz.2). Fix also indentation.
> Fix databox

- stage6/02-adi-update-tools/00-run.sh
The command 'rm -rf gtkdatabox-1.0.0.tar.gz' is run inside the folder gtkdatabox-1.0.0 and there is no archive to delete. 
cd one level up and call rm command only afterwards. Switch also from cd to pushd/popd.
> stage6/02-adi-update-tools: fix databox deletion

- stage6/02-adi-update-tools/00-run.sh
- stage6/04-gnuradio-m2k/00-run.sh
Cherry-pick commits that got in main in the meanwhile and update libm2k to use v0.8.0 release tag instead of next_stable.
> 2022 r2 fixes

- Dockerfile
- README.md
- config
- kuiper-stages.sh
- stages/07.export-stage/03.export-image/configure-setup.sh
- stages/07.export-stage/03.export-image/run.sh
Add option to prepare the boot partition
The boot partition can be prepared with required boot files in order to boot a specific project on a specific board. The PROJECT_NAME and BOARD can be set in the config file. Project description is retrieved from kuiper.json. The configuration is done in 07.export-stage/03.export-image. After built, Kuiper will be ready to boot with no additional configuration.
> Add option to prepare the boot partition

- .github/workflows/kuiper2_0-build.yml
- README.md
Migrate the build from Azure Devops on GitHub Actions
> Add GitHub build

- README.md
- stages/04.configure-desktop-env/01.desktop-env/run.sh
- stages/07.extra-tweaks/03.install-rpi-wifi-firmware/run.sh
RPI wifi firmware does not depend on desktop environment now, so it can be moved to stage 07.extra-tweaks/03.install-rpi-wifi-firmware
> Move RPI wifi firmware installation to stage 07

- stage6/03-pyadi/00-run.sh
Instead of latest tag, v.0.0.16- which is from August 2023, install pyadi-iio from latest
main. It contains support for iio-osc navassa profile generator and other fixes.
> stage6/03-pyadi:install pyadi-iio from latest main

- .github/workflows/docker-image-build.yml
- .github/workflows/kuiper2_0-build.yml
- ci/Dockerfile
This PR adds a new functionality to the building process were docker images for 32 and 64 bits basic configurations are created automatically when a new push is made on the default branch for kuiper2.0
> Kuiper docker image

- .github/workflows/docker-image-build.yml
Export docker images of kuiper2.0 also on github packages section of the repository page.
> Add docker images export on github packages

- stages/03.system-tweaks/05.automount/00.install-packages/packages
- stages/03.system-tweaks/05.automount/files/udiskie.service
- stages/03.system-tweaks/05.automount/run.sh
Install udiskie: lightweight automounter daemon for removable media on Linux. 
Install and enable udiskie.service file.
> 03.system-tweaks: configure automounting

- stages/05.adi-tools/11.install-gnuradio/files/trixie.list
- stages/05.adi-tools/11.install-gnuradio/run.sh
- stages/08.export-stage/02.export-sources/01.deb-src-chroot/run-chroot-deb.sh
- stages/08.export-stage/02.export-sources/run.sh
Switch to GNU Radio 3.10.5 (from Debian 12) because the previous installed version (GNU Radio 3.10.8 from Debian 13) breaks packages.
Update the flow for exporting sources.
> Switch to GNU Radio 3.10.5

- stage6/03-pyadi/00-run.sh
Since there was create a new release tag for pyadi-iio, switch the installation to it, instead of latest main.
> stage6/03-pyadi: switch installation to latest tag

- stage8/00-license-generation/00-run.sh
Update kernel version in license and remove HDL TB repo since it isn't part of Kuiper image
> Update kernel version in license and remote HDL TB repo since it isn't part of Kuiper image

- stage2/01-sys-tweaks/00-packages
- stage3/00-install-packages/00-packages
- stage4/00-install-packages/00-packages
- stage4/05-print-support/00-packages
- stage6/01-install-packages/00-packages
policykit-1:	            stage2/01-sys-tweaks/00-packages AND stage3/00-install-packages/00-packages
raspberrypi-net-mods: stage2/02-net-tweaks/00-packages AND stage4/00-install-packages/00-packages
curl:                             stage2/01-sys-tweaks/00-packages AND stage6/01-install-packages/00-packages
git:                               stage3/00-install-packages/00-packages AND stage6/01-install-packages/00-packages
python3-numpy:          stage4/00-install-packages/00-packages AND stage6/01-install-packages/00-packages
python3-pyqt5             stage6/01-install-packages/00-packages TWICE
Remove unused package: system-config-printer
Change python3-rpi-lgpio to python3-rpi.gpio because Kuiper starts from Debian 11 and `python3-rpi-lgio` is a Debian 12 package
> Remove duplicates

- stages/06.boot-partition/02.rpi-boot-files/files/config.txt
Enable DWC2 host mode support for CM5 by default
> 06.boot-partition/02.rpi-boot-files/config: Add support for CM5

- stage8/00-license-generation/00-run.sh
Fix broken links of the existing licenses
Update repositories names
Add licenses for pyadi, libm2k, iio-fm-radio, jesd-eye-scan-gtk, colorimeter, grm2k, linux-image-ADI_scripts
> stage8/00-license-generation: fix broken links

- stages/08.export-stage/02.export-sources/run.sh
Salsa link for debootstrap sources was broken. Changed to downloading sources via apt.
> 08.export-stage/02.export-sources: Download debootstrap sources via apt

- stages/08.export-stage/02.export-sources/run.sh
Download sources for pip installed packages.
> 08.export-stage/02.export-sources: Download sources for pip

- .github/workflows/docker-image-build.yml
- .github/workflows/kuiper2_0-build.yml
Export two artifacts, one that contains only the zip with the image and the other with the meta files generated during build time.
> .github/workflows: separate export of the image and meta files

- stages/03.system-tweaks/04.network-tweaks/run.sh
Disable Predictable Network Interface names by linking the "99-default.link" and "73-usb-net-by-mac.link" to /dev/null.
The corresponding files are located in "/usr/lib/systemd/network", but because udev follows this precedence:
- /etc/systemd/network - highest priority
- /run/systemd/network
- /usr/lib/systemd/network
The best option is to link to null "99-default.link" and "73-usb-net-by-mac.link" files from the folder with the higher priority, even in they were not existent there before. This ensures that any other change made to the system will not override the option to disable Predictable Network Interface names unless explicitly removing the created links.
The previous implementation overrode predictable network interface names, which resulted in race conditions between services …
> 03.system-tweaks: disable Predictable Network Interface names

- stages/03.system-tweaks/02.root-autologin/run.sh
Add an ANSI reset code at the begining of /etc/issue to clear any text formatting from boot messages.
> 03.system-tweaks/02.root-autologin: Reset terminal text formatting

- stages/03.system-tweaks/04.network-tweaks/files/Wired connection 1
- stages/03.system-tweaks/04.network-tweaks/files/eth0-linklocal
- stages/03.system-tweaks/04.network-tweaks/run.sh
Created nmconnection files for eth0 to handle IP assignments when network cables are plugged into different types of hosts: DHCP servers or standalone PCs. "Wired connection 1":
- the default connection created by NetworkManager
- tries DHCP on eth0 (method=auto)
- fails in 5 seconds if no DHCP server is available (dhcp-timeout=5)
- has a high priority (autoconnect-priority=10) making it the preferred connection
- won't consider it a failure (may-fail=false) and will keep retrying if a DHCP server appears
- IPV6 is disabled
"eth0-linklocal":
- the custom connection profile for IP assignment via link-local for standalone PCs
- uses method=link-local for addressing 169.254.x.x range
- lower autoconnect-priority (5) so it only activates if the higher-priority one ("Wired connection 1") fails …
> 03.system-tweaks/04.network-tweaks: Add custom NM profiles

- stages/05.adi-tools/12.install-gr-m2k/run.sh
Temorary fix until I manage the get the better, elegant fix into the gnuradio package.
The build for gr-m2k used to fail because, when configuring gnuradio, the cmake project couldn't find the gmp libraries.
The problematic search is implemented in
/usr/lib/aarch64-linux-gnu/cmake/gnuradio/FindGMP.cmake.
Function pkg_check_modules is used to search for the gmp libraries initially but fails. It is followed by fallback calls of find_library. Those also fail because of some magic cmake internal variable probably set by the failed pkg_check_modules function initial call.
The fallback functions work fine on their own.
In order to temporary solve this issue, remove the pkg_check_modules call from FindGMP.cmake. After gr-m2k is installed, restore the original FindGMP.cmake file.
> 05.adi-tools/12.install-gr-m2k: Temporarily fix gmp

- stages/06.boot-partition/03.add-fstab/files/README.txt
- stages/06.boot-partition/03.add-fstab/run.sh
Add a README file in the boot partition now that boot files will be installed separately from ADI APT repo.
> 06.boot-partition: Add README file in image
